version: '2'
services:
    php70:
        build: .
        image: zailing/php70
        container_name: php70
        hostname: php70
        privileged: true
        read_only: false
        tty: false
        network_mode: "bridge"
        
        ulimits:
            nofile:
                soft: 102400
                hard: 102400
                        
        ports:
            - "127.0.0.1:2253:22"
            - "80:80"
            - "443:443"
            - "1080:1080"
            - "8080:8080"
            
        volumes:
            - /opt/docker/php70/www:/www
            - /opt/docker/php70/logs:/var/log/nginx
            - /opt/docker/php70/conf:/etc/nginx/ext.d
        
        environment:
            - NGINX_GENERATE_DEFAULT_VHOST=true
            
        dns: 202.106.0.20
        
        extra_hosts:
            - "gp.wfuzz.com:192.168.10.152"
            - "www.phpmyadmin.com:192.168.10.149"
            - "api.wfuzz.com:192.168.1.2"
            
        
        
        
           
